"""create user table

Revision ID: 1a2554558568
Revises: ef60884a6600
Create Date: 2023-08-13 22:18:38.664761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2554558568'
down_revision: Union[str, None] = 'ef60884a6600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('post', sa.Column('last_modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'last_modified_at')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
